# Uses https://github.com/yvesgurcan/deploy-lambda-function

name: Deploy Lambda
on:
  push:
    branches: [ main ]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - run: cat src/requirements.txt | xargs -n 1 python3 -m pip install --target package/
      - run: cp src/free_cfa.py src/get_name_and_number.py src/send_text.py package
      - run: cd package/ && zip -r ../package.zip **
      - uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          package: package.zip
          function-name: blackhawks-cfa-texter
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-backend-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: zip -j lambda.zip ./backend/index.mjs
      - run: aws lambda update-function-code --function-name=BlackhawksCfaBackend --zip-file=fileb://lambda.zip

  deploy-frontend-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp frontend/index.html s3://${{ secrets.bucket_name }}/index.html